# Generated by Django 2.2.12 on 2020-04-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200302_1915'),
        ('polls', '0007_auto_20180813_2050'),
    ]

    operations = [
    ]
