# Generated by Django 2.2.12 on 2020-04-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_merge_20200406_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'permissions': (('show_poll', 'User/Group is allowed to view that poll'), ('vote_poll', 'User/Group is allowed to participate (vote) in that poll')), 'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
    ]
